feat: improve setting ui in UI.wl, add OpenAi Chat Completion URL settings
WolframResearch/Chatbook pull request #456
Opened 2023-11-15 06:56 UTC by nhannht

```txt
Now you can change the default endpoint to anything you want. 
```

Hello, this repo is pretty big, I try not to mess with the  current code base but if I do something wrong, feel free to fix it if you have time 

There are typical cases in which the user didn't fetch data from the official OpenAi url but from some kind of proxy, that is why I added this minor change.

![image](https://github.com/WolframResearch/Chatbook/assets/69144096/8506cc62-d9eb-4e4b-b8f1-8722fa0f4902)

By default, the official URL will be used, but now people can freely change it to something else like `http://localhost:8080/v1/chat/completions/`.

2023-11-15 14:56 UTC, bobohilario commented
This seems like a good idea. Two small changes to make for consistency:
- Do not change the gitignore file
- Please use "OpenAI" with a capital I instead of "OpenAi" and "API" all capital instead of "Api" everywhere.

2023-11-15 15:12 UTC, nhannht commented
Sorry, I was confused when I looked at the CI checking, did the engine in the docker image have a problem with the license? 

![image](https://github.com/WolframResearch/Chatbook/assets/69144096/e2d7a7db-243f-4a83-9829-b6bc89ca11d6)

This is the screenshot from when I ran it on my local machine
![image](https://github.com/WolframResearch/Chatbook/assets/69144096/07b2c5c4-b19c-4f6d-8226-b4768f493702)

![image](https://github.com/WolframResearch/Chatbook/assets/69144096/b3f8943e-28e8-467c-830d-49f2e5e18010)


![image](https://github.com/WolframResearch/Chatbook/assets/69144096/6d783422-1aa9-4df1-b18c-b76052d09b46)

2023-11-15 19:01 UTC, rhennigan requested changes
This looks great, though there are a few changes we'd like before merging (see comments).

Also, you may have noticed in the code that there are two paths for submitting the chat request, depending on whether LLMServices is available ([here](https://github.com/WolframResearch/Chatbook/blob/07c8788ca52d1d890e82ff08abd78515745094c4/Source/Chatbook/SendChat.wl#L68) and [here](https://github.com/WolframResearch/Chatbook/blob/07c8788ca52d1d890e82ff08abd78515745094c4/Source/Chatbook/SendChat.wl#L186)). In 14.0+, the LLMServices method will be the way that requests are submitted, so your changes wouldn't have any affect in future versions. However, I think this is still definitely a useful feature for 13.3 users.

2023-11-15 19:01 UTC, rhennigan commented on Source/Chatbook/UI.wl
> +		ImageSize -> {180, Automatic},
This should avoid line breaks in the input field for the default URL:
```suggestion
		ImageSize -> {240, Automatic},
```

2023-11-15 19:01 UTC, rhennigan commented on Source/Chatbook/UI.wl
> +				tr["Default OpenAi Chat Completion Endpoint"],
* This shouldn't say "Default" like the other controls, because it's a global setting that you don't set the notebook or cell level.
* The label could also be shortened a bit and made less technical.
* It should have a colon at the end for consistency with the other labels.

```suggestion
				tr["Chat Completion URL:"],
```

2023-11-15 19:01 UTC, rhennigan commented on Source/Chatbook/SendChat.wl
> +        apiCompletionURL = ConfirmBy[ Lookup[ settings, "OpenAiApiCompletionURL" ], StringQ ];
These "OpenAiApiCompletionURL" strings should be replaced with "OpenAIAPICompletionURL" (capitalization).
```suggestion
        apiCompletionURL = ConfirmBy[ Lookup[ settings, "OpenAIAPICompletionURL" ], StringQ ];
```

2023-11-16 05:08 UTC, nhannht commented
If you have time can you consider checking my newest fix 🤗

2023-11-16 15:11 UTC, rhennigan approved these changes

2023-11-17 02:27 UTC, nhannht commented
Thank you, I tried to read all 3 links, I can grasp at least a basic. (to be honest, this is the first time I have tried to read these kind of documents 😄)

I understood and agreed with all the terms below :
https://github.com/WolframResearch/Chatbook/blob/main/CONTRIBUTING.md?rgh-link-date=2023-11-16T15%3A11%3A16Z
![image](https://github.com/WolframResearch/Chatbook/assets/69144096/1818144c-e4e3-4b4d-b59f-dcd7ce355d01)

2023-11-20 17:37 UTC, merged